### ISSUE TITLE
Certificat SSL expiré

### ISSUE THREAD

**Issue by pyrsmk** [sgmap/inspire#1058]
Notre geocoder nous retourne des erreurs de certificat SSL expiré sur l'adresse `https://api-adresse.data.gouv.fr/` depuis aujourd'hui.

Pouvez vous le renouveler ?

**Comment by pyrsmk** [comment]
Mmmh... Il semble que le problème est interne à nos serveurs. Je ferme ce ticket et le rouvrirai s'il s'avère au final qu'il y a bien un soucis de votre côté.

**Comment by ThomasG77** [comment]
Toujours d'actualité maintenant? Ne reproduit pas avec https://api-adresse.data.gouv.fr/search/?q=1%20route%20de%20Vannes
Cela peut être lié au certificat de Let's Encrypt qui a expiré https://twitter.com/letsencrypt/status/1443621997288767491 ?!
Un certain nombre de sites ont été affectés

**Comment by pyrsmk** [comment]
Ca a clairement l'air d'être ça le problème. Merci de m'avoir pointé ce tweet car ça me faisait tourner en bourrique 😅

**Comment by pyrsmk** [comment]
@ThomasG77 Un peu plus d'infos sur comment régler le soucis : https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

Je vous invite à jeter un oeil au troisième workaround, à destination des serveurs.
