### ISSUE TITLE
Doc - A quoi correspond la référence à Isogeo?

### ISSUE THREAD

**Issue by gryckelynck** [sgmap/inspire#6]
Dans la doc (cf. [README_csw2datagouvfr.md](https://github.com/sgmap/inspire/blob/master/doc/README_csw2datagouvfr.md)) on peut lire 
> Une fois votre flux CSW créé dans Isogeo, 

1. Le lien renvoie une erreur 404 (https://github.com/sgmap/inspire/blob/master/fr/features/publish/csw_server.html)
2. A quoi correspond cette référence à IsoGéo?

**Comment by jdesboeufs** [comment]
Une coquille laissée par @Guts ;)

**Comment by Guts** [comment]
Je fais une passe pour nettoyer les références.

**Comment by Guts** [comment]
Corrigé avec https://github.com/sgmap/inspire/commit/bb532f80f9cd8cc372ecad36a813cd59a96f5d00
